### ISSUE TITLE
how to connect Login Admin

### ISSUE THREAD

**Issue by NemmarS** [ajayrandhawa/User-Management-PHP-MYSQL#23]
Login issue Please Help me i need This
![11](https://user-images.githubusercontent.com/115891544/195998847-b706973f-c562-4fc4-ade4-116b7735ccf5.png)
![12](https://user-images.githubusercontent.com/115891544/195998910-826565fb-f014-439d-a06d-8b169ab44129.png)
![13](https://user-images.githubusercontent.com/115891544/195998913-be07f798-4764-4719-ab7d-42611d68043d.png)

**Comment by drmuzic** [comment]
From the looks of your database (admin) and the user information on the screen, the password is stored in PLAIN text when the script stored passwords in the database using the outdated MD5 hashing. Whem the script logs you in, it cannot compare plain text passwords stored in the database because it is plain text. Replace your password with the password data in the database.sql file as it is hashed, login to the admin section and change the password how you see fit.
You log in to the admin section of this from localhost/admin/index.php (this looks so close to webadmin.com's User Management System).
